### ISSUE TITLE
Create an endpoint to list all connections

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-controller#239]
Hi,

As we discussed during SDX meeting, we should have an endpoint to list all the connections. We currently have one endpoint to create connection, we have another one for DELETE a connection, and we have one for GET a specific connection (by connection ID). It would be nice if we have an endpoint for listing ALL the connections.

**Comment by italovalcy** [comment]
Hi team,

Any updates on this issue? @usmanazFIU is currently working on Meican side to have a dashboard that lists all the connections, but since SDX-Controller does not provide such feature, we are stuck waiting on this feature. Please let us know if we can help with anything.

**Comment by YufengXin** [comment]
This is the next in the pipeline, no update for now. 
On the other hand, I would suggest to have an independent unittest for Meican.

**Comment by italovalcy** [comment]
> This is the next in the pipeline, no update for now. On the other hand, I would suggest to have an independent unittest for Meican.

Hi Yufeng, have you had any chance of looking into this issue on the last days? If  no, what do you think about start modeling how would a reply to this endpoint looks like? Can we assume it will be an array of connection objets (like the endpoint that provides information on an individual connection) ?

**Comment by sajith** [comment]
It is not clear to me what do we mean when we say "all the connections".  (Part of the reason is that we've been using "connection" and "connection request" interchangeably now and then. We should clear that also up.)

There would be some active/successful connections, some failed ones, some completed ones, and some in progress (or yet to be made, or in the "submitted" state).  If we're to include all of these, the list of connections will grow over time.

Should `GET /connections` return all of them?  Should it return a list of connection IDs (I think this response would be more compact), and then let clients do `GET /connection/:connection_id` if they want details?

**Comment by YufengXin** [comment]
@italovalcy given the ambiguity of the requirement (in general, the endpoint specification) as Sajith stated, for now,  let's send back all the connections the sdx-controller received.

@congwang09 has implemented the necessary changes in the db and the controller and is testing it. There has been a PR pending merge.
